<?php

$testOptions = [];

/** @var array $tests will be available from IndexController->startAction();*/
foreach ($tests as $test) {
    /** NB: $test would normally be an entity with properties. Simple array used here for brevity */
    $testOptions[] = '<option value=' . $test['id'] . '">' . $test['name'] . '</option>';
}

// todo: add Bootstrap for for Responder email and test option

/** NB: this partial template would normally be rendered as part of the module layout. Simply HTML used here */
?>
<html>
<body>
<div class="container">
    <div class="row">
        <form>

        </form>
    </div>
</div>
</body>
</html>
